### ISSUE TITLE
Problem in creating report when "TEST_FAIL"

### ISSUE THREAD

**Issue by filosi** [genepi/nf-gwas#78]
Process Report return this error when the regenie test fails and LOG10P -> NA

```
  java.lang.NumberFormatException: For input string: "NA"
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.base/java.lang.Double.parseDouble(Double.java:651)
        at genepi.io.table.reader.AbstractTableReader.getDouble(AbstractTableReader.java:38)
        at genepi.io.table.reader.AbstractTableReader.getDouble(AbstractTableReader.java:30)
        at genepi.genomic.utils.commands.GwasReportCommand.createHtmlReport(GwasReportCommand.java:316)
        at genepi.genomic.utils.commands.GwasReportCommand.call(GwasReportCommand.java:216)
        at genepi.genomic.utils.commands.GwasReportCommand.call(GwasReportCommand.java:31)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at genepi.genomic.utils.App.main(App.java:38)
```

See also: https://github.com/genepi/genomic-utils/issues/5

**Comment by lukfor** [comment]
Thanks. It's fixed and available in the next release 👍

**Comment by filosi** [comment]
I tried again to test with the last genomic-utils release 0.3.6 included in the last build of the nf-gwas docker but I got the same error at the FILTER_RESULTS step:
```
 java.lang.NumberFormatException: For input string: "NA"                                                                                                                                                          
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)                                                                                                             
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)                                                                                                                       
        at java.base/java.lang.Double.parseDouble(Double.java:651)                                                                                                                                                 
        at java.base/java.lang.Double.valueOf(Double.java:614)                                                                                                                                                     
        at genepi.genomic.utils.commands.csv.CsvFilterCommand.call(CsvFilterCommand.java:103)                                                                                                                      
        at genepi.genomic.utils.commands.csv.CsvFilterCommand.call(CsvFilterCommand.java:16)                                                                                                                       
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)                                                                                                                                            
        at picocli.CommandLine.access$1500(CommandLine.java:148)                                                                                                                                                   
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at genepi.genomic.utils.App.main(App.java:68)
```
Resulting in failing the next steps of the pipeline
I guess it's related with the https://github.com/genepi/genomic-utils/issues/5 which seems not solve in the last release 0.3.6.

**Comment by seppinho** [comment]
Hi, thanks!! This should be fixed in v1.0.1. Let us know if it works!
Best
