### ISSUE TITLE
'Nextflow.exit(int,String)'  doesn't support array

### ISSUE THREAD

**Issue by lindenb** [genepi/nf-gwas#90]
Hi,
I got the following error message

```
Missing process or function exit([1, Parameter genotypes_prediction is required.])`
```

with stacktrace:
```
Caused by: groovy.lang.MissingMethodException: No signature of method: static WorkflowMain.exit() is applicable for argument types: (Integer, String) v
alues: [1, Parameter genotypes_prediction is required.]
Possible solutions: wait(), wait(long), wait(long, int), getAt(java.lang.String), grep(), dump()
        at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1570)
        at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1556)
        at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.callStatic(StaticMetaClassSite.java:62)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
(...)
````

using NF 23.10.0 .

it looks like Nextflow.exit https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/Nextflow.groovy#L196 doesn't accept array/vector

**Comment by seppinho** [comment]
Thanks @lindenb. We already openend a [pull request](https://github.com/genepi/nf-gwas/pull/97) to fix this.

**Comment by seppinho** [comment]
Fixed by https://github.com/genepi/nf-gwas/pull/97
